spring.application.name=File-Upload-System

spring.datasource.driver-class-name= com.mysql.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/fileDb?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.generate-ddl=true
spring.jpa.hibernate-ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=EZKjQ5ib070dBSK28wNaHAMFbVsk4mYdb3pr56KFKsI
jwt.expiration=86400000
